# conve-KvsAll-kl-bo-best
# conve-KvsAll-kl-bo
# wnrr-conve-KvsAll-kl
job.type: search
search.type: ax
dataset.name: wnrr

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True

# this is faster for smaller datasets, but does not work for some models (e.g.,
# TransE due to a pytorch issue) or for larger datasets. Change to spo in such
# cases (either here or in ax section of model config), results will not be
# affected.
negative_sampling.implementation: sp_po

# validation/evaluation settings (fixed)
valid:
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  filter_with_test: True
  early_stopping:
    patience: 10
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256
  metrics_per.relation_type: True

# settings for reciprocal relations (if used)
import: [conve, reciprocal_relations_model]
reciprocal_relations_model.base_model.type: conve

# ax settings: hyperparameter serach space
ax_search:
  num_trials: 5
  num_sobol_trials: 10 
  parameters:
      # model
    - name: model
      type: fixed
      value: reciprocal_relations_model

    # training hyperparameters
    - name: train.batch_size
      type: fixed
      value: 1024
      is_ordered: True
    - name: train.type
      type: fixed
      value: KvsAll
    - name: train.optimizer
      type: fixed
      value: Adam
    - name: train.loss
      type: fixed
      value: kl
    - name: train.optimizer_args.lr     
      type: fixed
      value: 0.0016227612377289686
      log_scale: True
    - name: train.lr_scheduler
      type: fixed
      value: ReduceLROnPlateau
    - name: train.lr_scheduler_args.mode
      type: fixed
      value: max  
    - name: train.lr_scheduler_args.factor
      type: fixed
      value: 0.95  
    - name: train.lr_scheduler_args.threshold
      type: fixed
      value: 0.0001  
    - name: train.lr_scheduler_args.patience
      type: fixed
      value: 1

    # embedding dimension
    - name: lookup_embedder.dim
      type: fixed
      value: 512
      is_ordered: True

    # embedding initialization
    - name: lookup_embedder.initialize
      type: fixed
      value: xavier_normal_
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: fixed
      value: 7.846665989552367e-05
      log_scale: True
    - name: lookup_embedder.initialize_args.uniform_.a
      type: fixed
      value: -0.24193942744314623
    - name: lookup_embedder.initialize_args.xavier_uniform_.gain
      type: fixed
      value: 1.0
    - name: lookup_embedder.initialize_args.xavier_normal_.gain
      type: fixed
      value: 1.0

    # embedding regularization
    - name: lookup_embedder.regularize
      type: fixed
      value: l1
      is_ordered: True
    - name: lookup_embedder.regularize_args.weighted
      type: fixed
      value: False
    - name: conve.entity_embedder.regularize_weight
      type: fixed
      value: 1.0796528707620546e-08
      log_scale: True
    - name: conve.relation_embedder.regularize_weight
      type: fixed
      value: 9.522894656684954e-11
      log_scale: True

    # embedding dropout
    - name: conve.entity_embedder.dropout
      type: fixed
      value: -0.03126845036454501
    - name: conve.relation_embedder.dropout
      type: fixed
      value: 0.2266267972032251

    # training-type specific hyperparameters
    - name: KvsAll.label_smoothing            #train_type: KvsAll
      type: fixed
      value: -0.17361994040496875
    # model-specific entries
    - name: conve.feature_map_dropout
      type: fixed
      value: 0.3318920246589899
    - name: conve.projection_dropout
      type: fixed
      value: 0.1498818066974686
    - name: conve.convolution_bias
      type: fixed
      value: False
    - name: conve.round_dim
      type: fixed
      value: True