dataset:
  name: toy

job:
  device: cuda
  type: search

checkpoint:
  every: 5

KvsAll:
  label_smoothing: -1.0

train:
  batch_size: 512
  loss: bce
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    factor: 0.95
    patience: 0
    threshold: 0.0001
  max_epochs: 200
  num_workers: 0
  optimizer: Adam
  optimizer_args:
    +++: +++
    lr: 0.1
  pin_memory: false
  trace_level: epoch
  type: KvsAll
  auto_correct: True

user:
  +++: +++

valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
  every: 5
  filter_with_test: true
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: ''
  trace_level: epoch

eval:
  batch_size: 256
  data: valid
  num_workers: 0
  pin_memory: false
  trace_level: example
  type: entity_ranking

import: sd_rescal
model: sd_rescal

sd_rescal:
  class_name: SparseDiagonalRescal
  blocks: -1
  round_blocks_to: [1, 2, 4, 8, 16, 32, 64, 128]
  block_size: -1
  round_block_size_to: []
  entity_embedder:
    type: lookup_embedder
    dim: -1
    round_dim_to: [128, 256, 512]
    +++: +++
  relation_embedder:
    type: lookup_embedder
    dim: -1 # is determined automatically from blocks, block_size and/or entity_dim
    +++: +++

lookup_embedder:
  class_name: LookupEmbedder
  dim: -1
  dropout: 0.0
  regularize: 'l2'
  regularize_args:
    weighted: True
    weight: 1.0e-10
  sparse: false

search:
  num_workers: 2
  type: ax
  device_pool: [cuda:0]

ax_search:
  num_trials: 40
  num_sobol_trials: 20
  fixed_parameters: []
  parameters:
    - name: train.batch_size
      type: fixed
      value: 1024
    - name: train.max_epochs
      type: fixed
      value: 300
    - name: train.optimizer_args.lr
      type: range
      log_scale: true
      bounds: [1.e-4, 1.0]
    - name: train.lr_scheduler_args.patience
      type: range
      bounds: [1,10]
    - name: train.optimizer
      type: choice
      values: [Adam, Adagrad]
    - name: sd_rescal.entity_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: sd_rescal.relation_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: KvsAll.label_smoothing
      type: range
      bounds: [-0.5, 0.5]
    - name: lookup_embedder.regularize_args.weight
      type: range
      log_scale: true
      bounds: [1.e-20, 1.e-5]
    - name: lookup_embedder.regularize_args.weighted
      type: choice
      is_ordered: True
      values: [True, False]
    - name: sd_rescal.entity_embedder.dim
      type: range
      log_scale: true
      bounds: [128, 512]
    - name: sd_rescal.blocks
      type: range
      log_scale: true
      bounds: [1, 128]
