# transe-negative_sampling-kl-bo-best
# transe-negative_sampling-kl-bo
# fb15k-237-transe-negative_sampling-kl
job.type: search
search.type: ax
dataset.name: fb15k-237

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True

# this is faster for smaller datasets, but does not work for some models (e.g.,
# TransE due to a pytorch issue) or for larger datasets. Change to spo in such
# cases (either here or in ax section of model config), results will not be
# affected.
negative_sampling.implementation: sp_po

# validation/evaluation settings (fixed)
valid:
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  filter_with_test: True
  early_stopping:
    patience: 10
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256
  metrics_per.relation_type: True

# settings for reciprocal relations (if used)
import: [transe, reciprocal_relations_model]
reciprocal_relations_model.base_model.type: transe

# ax settings: hyperparameter serach space
ax_search:
  num_trials: 5
  num_sobol_trials: 10 
  parameters:
      # model
    - name: model
      type: fixed
      value: reciprocal_relations_model

    # training hyperparameters
    - name: train.batch_size
      type: fixed
      value: 128
      is_ordered: True
    - name: train.type
      type: fixed
      value: negative_sampling
    - name: train.optimizer
      type: fixed
      value: Adam
    - name: train.loss
      type: fixed
      value: kl
    - name: train.optimizer_args.lr     
      type: fixed
      value: 0.00030000000000000014
      log_scale: True
    - name: train.lr_scheduler
      type: fixed
      value: ReduceLROnPlateau
    - name: train.lr_scheduler_args.mode
      type: fixed
      value: max  
    - name: train.lr_scheduler_args.factor
      type: fixed
      value: 0.95  
    - name: train.lr_scheduler_args.threshold
      type: fixed
      value: 0.0001  
    - name: train.lr_scheduler_args.patience
      type: fixed
      value: 5

    # embedding dimension
    - name: lookup_embedder.dim
      type: fixed
      value: 128
      is_ordered: True

    # embedding initialization
    - name: lookup_embedder.initialize
      type: fixed
      value: uniform_
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: fixed
      value: 3.5688807324453804e-05
      log_scale: True
    - name: lookup_embedder.initialize_args.uniform_.a
      type: fixed
      value: -1.0000000000065512e-05
    - name: lookup_embedder.initialize_args.xavier_uniform_.gain
      type: fixed
      value: 1.0
    - name: lookup_embedder.initialize_args.xavier_normal_.gain
      type: fixed
      value: 1.0

    # embedding regularization
    - name: lookup_embedder.regularize
      type: fixed
      value: ''
      is_ordered: True
    - name: lookup_embedder.regularize_args.weighted
      type: fixed
      value: False
    - name: transe.entity_embedder.regularize_weight
      type: fixed
      value: 3.734744372755937e-12
      log_scale: True
    - name: transe.relation_embedder.regularize_weight
      type: fixed
      value: 9.090088454020142e-08
      log_scale: True

    # embedding dropout
    - name: transe.entity_embedder.dropout
      type: fixed
      value: -0.3519595685173064
    - name: transe.relation_embedder.dropout
      type: fixed
      value: -0.17305121371616672

    # training-type specific hyperparameters
    - name: negative_sampling.num_negatives_s #train_type: negative_sampling
      type: fixed
      value: 61
      log_scale: True                         #train_type: negative_sampling
    - name: negative_sampling.num_negatives_o #train_type: negative_sampling
      type: fixed
      value: 192
      log_scale: True                         #train_type: negative_sampling
    # model-specific entries
    - name: transe.l_norm
      type: fixed
      value: 2.0
      is_ordered: True
    - name: transe.entity_embedder.normalize.p
      type: fixed
      value: -1.0
    - name: transe.relation_embedder.normalize.p
      type: fixed
      value: -1.0
    - name: negative_sampling.implementation
      type: fixed
      value: spo